/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaksin;

import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class Asking extends javax.swing.JFrame {

    /**
     * Creates new form Asking
     */
    public Asking() {
        initComponents();
    }
    
    private String jenis;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jenisVaksin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        belum = new javax.swing.JRadioButton();
        button1 = new java.awt.Button();
        mmr = new javax.swing.JCheckBox();
        tiroid = new javax.swing.JCheckBox();
        pentavalen = new javax.swing.JCheckBox();
        rotavirus = new javax.swing.JCheckBox();
        vaksin = new javax.swing.JCheckBox();
        pneumokokus = new javax.swing.JCheckBox();
        influenza = new javax.swing.JCheckBox();
        hepatitisa = new javax.swing.JCheckBox();
        hepatitisb = new javax.swing.JCheckBox();
        campak = new javax.swing.JCheckBox();
        vaksinbcg = new javax.swing.JCheckBox();

        jLabel2.setText("1. APAKAH SUDAH PERNAH MELAKUKAN VAKSIN ?");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID "+onKush.id_anak);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APAKAH SUDAH PERNAH MELAKUKAN VAKSIN? JIKA SUDAH, JENIS APA?");

        belum.setBackground(new java.awt.Color(0, 255, 153));
        jenisVaksin.add(belum);
        belum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        belum.setText("Belum Pernah");
        belum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belumActionPerformed(evt);
            }
        });

        button1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        button1.setLabel("Lanjut");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        mmr.setBackground(new java.awt.Color(0, 255, 153));
        mmr.setText("VAKSIN MMR");

        tiroid.setBackground(new java.awt.Color(0, 255, 153));
        tiroid.setText("Vaksin Tiroid");
        tiroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiroidActionPerformed(evt);
            }
        });

        pentavalen.setBackground(new java.awt.Color(0, 255, 153));
        pentavalen.setText("Vaksin Pentavalen");
        pentavalen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pentavalenActionPerformed(evt);
            }
        });

        rotavirus.setBackground(new java.awt.Color(0, 255, 153));
        rotavirus.setText("Vaksin Rotavirus");
        rotavirus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotavirusActionPerformed(evt);
            }
        });

        vaksin.setBackground(new java.awt.Color(0, 255, 153));
        vaksin.setText("Vaksin");

        pneumokokus.setBackground(new java.awt.Color(0, 255, 153));
        pneumokokus.setText("Pneumokukus");

        influenza.setBackground(new java.awt.Color(0, 255, 153));
        influenza.setText("Vaksin Influenza");

        hepatitisa.setBackground(new java.awt.Color(0, 255, 153));
        hepatitisa.setText("Vaksin Hepatitis A");

        hepatitisb.setBackground(new java.awt.Color(0, 255, 153));
        hepatitisb.setText("Vaksin Hepatitis B");

        campak.setBackground(new java.awt.Color(0, 255, 153));
        campak.setText("Vaksin Campak");

        vaksinbcg.setBackground(new java.awt.Color(0, 255, 153));
        vaksinbcg.setText("Vaksin BCG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(belum, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(mmr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tiroid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pentavalen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rotavirus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vaksin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pneumokokus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(influenza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hepatitisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hepatitisb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vaksinbcg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(15, 15, 15)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(belum)
                .addGap(18, 18, 18)
                .addComponent(mmr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tiroid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pentavalen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotavirus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vaksin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pneumokokus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(influenza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hepatitisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hepatitisb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vaksinbcg)
                .addGap(28, 28, 28)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cekPernah(){
        if (belum.isSelected()){
            jenis="-Belum Pernah Vaksin-";
        } 
        else if (mmr.isSelected()){
            jenis="Vaksin MMR";
        }  else if(tiroid.isSelected()){
            jenis="Vaksin Tiroid";
        }  else if(pentavalen.isSelected()){
            jenis="Vaksin Pentavalen";
        } else if(rotavirus.isSelected()){
            jenis="Vaksin Rotavirus";
        } else if(vaksin.isSelected()){
            jenis="Vaksin";
        } else if(pneumokokus.isSelected()){
            jenis="Vaksin Pneumokokus";
        } else if(influenza.isSelected()){
            jenis="Vaksin Influenza";
        } else if(hepatitisa.isSelected()){
            jenis="Vaksin Hepatitis A";
        } else if(hepatitisb.isSelected()){
            jenis="Vaksin Hepatitis B";
        } else if(campak.isSelected()){
            jenis="Vaksin Campak";
        } else if(vaksinbcg.isSelected()){
            jenis="Vaksin BCG";
        }
        
    }
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        cekPernah();
        onKush.addAsking(onKush.id_anak, jenis);
        JFrame jadwal=new jadwal();
        jadwal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void belumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_belumActionPerformed

    private void rotavirusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotavirusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotavirusActionPerformed

    private void pentavalenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pentavalenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pentavalenActionPerformed

    private void tiroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiroidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiroidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton belum;
    private java.awt.Button button1;
    private javax.swing.JCheckBox campak;
    private javax.swing.JCheckBox hepatitisa;
    private javax.swing.JCheckBox hepatitisb;
    private javax.swing.JCheckBox influenza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jenisVaksin;
    private javax.swing.JCheckBox mmr;
    private javax.swing.JCheckBox pentavalen;
    private javax.swing.JCheckBox pneumokokus;
    private javax.swing.JCheckBox rotavirus;
    private javax.swing.JCheckBox tiroid;
    private javax.swing.JCheckBox vaksin;
    private javax.swing.JCheckBox vaksinbcg;
    // End of variables declaration//GEN-END:variables
}
